version: "3"
services:
  nico:
    tty: true
    stdin_open: true
    container_name: nico
    build:
      context: .
      dockerfile: .docker/image.dockerfile
      args:
        CRYPT64:
        UPDATE_DB:
    entrypoint: [ "/code/.docker/entrypoint.sh" ]
    restart: always
    depends_on:
      - redis
      - db
    env_file: .env
    environment:
      REDIS_URL: "redis://redis:6379"
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      NODE_ENV: "development"
    volumes:
      - .:/code:delegated
      - /code/node_modules
    ports:
      - "2121:2121"
  db:
    image: postgres:14.1
    restart: always
    container_name: nicodb
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql
    env_file: .env

  redis:
    image: redis
    container_name: nicoredis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdata:/redisdata
volumes:
  redisdata:
  dbdata:
